### PR TITLE
Transition Materials to a JSON based format.

### PR DESCRIPTION
**Pull request by keplersj**
This should clean up the code base up a bit I hope and make expanding the mod, and moving forward in the future, less painful.

### CODE REVIEW

**Comment by viliml** [comment]
So I suppose we could read the whole folder in the "current resourcepack", and load the materials and blocks dynamically?
They could be indexed by what they're made of, that should still be unique.
Instead of our unlocalized material and block names, we could just use the block for from the crafting recipe.

**Comment by viliml** [comment]
PROBLEM: Assets are client-only

**Comment by k2b6s9j** [comment]
Servers can access the assets directory in the Jarfile. I was just going to have so that the mod recursively searches the JSON asset directory and load accordingly.

**Comment by viliml** [comment]
What if a resourcepack wants to change it?

**Comment by k2b6s9j** [comment]
Hmm... I don't think it will matter for the most part because the mod will have already loaded the JSON before the client makes its changes.

**Comment by viliml** [comment]
Then there would be discrepancies between the client and server. What if a resourcepack sets the crash resistance to 100? When you crash, the boat is fine on the client but broken on the server
Instead of assets, it should be in a config file, but then defaults become problematic...

**Comment by k2b6s9j** [comment]
Could move them to just be in the jar, seperate from assets.

**Comment by viliml** [comment]
And then unzip them into the config directory? That could work, if you know how to unzip stuff...

**Comment by k2b6s9j** [comment]
Why not just read from the JAR?

**Comment by viliml** [comment]
So, you intend to keep it immutable, only instead of in new classes the new materials shall be defined through JSON?

**Comment by k2b6s9j** [comment]
Yeah. Less compiling. Less code to update. Just a JSON spec to maintain.

**Comment by k2b6s9j** [comment]
One day though. I can see making a mutable way of doing it.

**Comment by viliml** [comment]
So, all that's left is to read find a way to read the JSON from the mod jar. You have fun with that, I failed.

**Comment by viliml** [comment]
Oopsie, it seems that forEach() is only available in Java 8. I'm sure that can be replaced with a range for.
I currently only have access to my mobile internet with limited bandwidth, so I don't want to do git pushes and pulls.

**Comment by k2b6s9j** [comment]
for each() is Java 8. foreach() is Scala.

**Comment by viliml** [comment]
See wercker.

**Comment by k2b6s9j** [comment]
Yes. I saw the error. We can still use the code, it just needs to use the Scala syntax, not the Java 8 syntax.

**Comment by viliml** [comment]
What _exactly_ is left to do?

**Comment by keplersj** [comment]
Leaving this branch up, but closing this PR because it's grown stale.

**Comment by viliml** [comment]
Which part of this project hasn't?

Vilim Lendvaj

**Pull request closed without merging**
